<?php
use Illuminate\Support\Facades\Auth;
use App\Models\Admin\TipoProducto;
use App\Models\Admin\Marca;
use App\Models\Admin\Modelo;
use Illuminate\Http\Request;
use App\Models\Admin\Imagen;
use App\Models\Admin\Producto;
use App\Models\Admin\Gasto;
use App\Models\Admin\Bitacora;
use App\Models\Admin\Documento;
use App\Mail\ProductoSend;

Route::get('admin/', function () {
    if (Auth::check()) {
        return redirect('admin/pedidos');
    }
    return view('admin.auth.login');
});

Route::group(['middleware' => ['auth','admin'],'prefix' => 'admin'], function () {    

    Route::get('/pedidos', '\App\Http\Controllers\Admin\DashboardController@index')->name('home');
    Route::post('/gastos/create', '\App\Http\Controllers\Admin\HomeController@addGastos')->name('gastos.create');
    Route::post('/gastos/delete', '\App\Http\Controllers\Admin\HomeController@delGastos')->name('gastos.delete');
    Route::post('/bitacoras/create', '\App\Http\Controllers\Admin\HomeController@addbitacoras')->name('bitacoras.create');
    Route::post('/bitacoras/delete', '\App\Http\Controllers\Admin\HomeController@delbitacoras')->name('bitacoras.delete');
    Route::post('/documentos/create', '\App\Http\Controllers\Admin\HomeController@adddocumentos')->name('documentos.create');
    Route::post('/documentos/delete', '\App\Http\Controllers\Admin\HomeController@delDocumentos')->name('documentos.delete');
    Route::get('/productos-unidades/create', '\App\Http\Controllers\Admin\HomeController@addProducto');
    Route::post('/productos-unidades/save/{id}', '\App\Http\Controllers\Admin\HomeController@saveProducto')->name('productos-unidades.save');
    Route::post('/productos-mx/save/{id}', '\App\Http\Controllers\Admin\HomeController@saveMxProducto')->name('productos-mx.save');
    Route::any('reporte-wishlist', '\App\Http\Controllers\Admin\HomeController@getWishlist');
    Route::resource('accesos', '\App\Http\Controllers\Admin\AccesosController');
    Route::resource('linea-negocios', '\App\Http\Controllers\Admin\LineaNegociosController');
    Route::resource('tipos-productos', '\App\Http\Controllers\Admin\TiposProductosController');
    Route::resource('marcas', '\App\Http\Controllers\Admin\MarcasController');
    Route::resource('modelos', '\App\Http\Controllers\Admin\ModelosController');
    Route::resource('clientes', '\App\Http\Controllers\Admin\ClientesController');
    Route::resource('noticias', '\App\Http\Controllers\Admin\NoticiasController');
    Route::resource('banners', '\App\Http\Controllers\Admin\BannersController');
    Route::resource('productos', '\App\Http\Controllers\Admin\ProductosController');
    Route::get('sortable/{table}', '\App\Http\Controllers\Admin\HomeController@getSortable');
    Route::get('pdf/{product_id}/', function($id){
        if(!$producto=Producto::find($id)){
            return view('404');
        }
        if($producto->mx==1){
            $pdf = PDF::loadView('admin.pdf.producto', ['producto'=>$producto]);
            return $pdf->download('reporte-de-'.$producto->nombre.'.pdf');
        }else{
            return view('404');
        }
    });
    Route::get('pdf/{type}/{product_id}/', function($type, $id){
        if(!$producto=Producto::find($id)){
            return view('404');
        }
        switch ($type) {
        	case 'gastos':
        		$data = Gasto::where('producto_id', $producto->id)->get();
        		break;
        	case 'bitacoras':
        		$data = Bitacora::where('producto_id', $producto->id)->get();
        		break;
        	default:
        		return view('404');
        		break;
        }

        if($producto->mx==1){
            $pdf = PDF::loadView('admin.pdf.producto_otros', ['data'=>$data, 'type'=>$type, 'producto'=>$producto]);
            return $pdf->download($type.'.pdf');
        }else{
            return view('404');
        }
    });
    Route::post('send-email-pro/{product_id}/', function(Request $req, $id){
        if(!$producto=Producto::find($id)){
            return view('404');
        }
        $gastos = Gasto::where('producto_id', $producto->id)->get();
        $accesos = DB::table('users')
                ->join('role_user', 'role_user.user_id', '=', 'users.id')     
                ->join('roles', 'role_user.role_id', '=', 'roles.id')
                ->where('roles.name','<>','cliente') 
                //->where('users.id','<>',Auth::user()->id)
                ->pluck('users.name', 'users.id')->toArray();
        $accesos['0'] = "Seleccione una opción";
        $bitacoras = Bitacora::where('producto_id', $producto->id)->get();
        $documentos = Documento::where('producto_id', $producto->id)->get();

        if($producto->mx==1){
            $pdf = PDF::loadView('admin.pdf.producto', ['documentos'=>$documentos, 'bitacoras'=>$bitacoras, 'producto'=>$producto,'gastos'=>$gastos]);
            $pdf->save(base_path('asset_admin/pdfs/'.$producto->nombre.'.pdf'));
            Mail::to(explode(',', $req->mail))->send(new ProductoSend($producto, base_path('asset_admin/pdfs/'.$producto->nombre.'.pdf')));
            return "Exito";
        }else{
            return view('404');
        }
    });
    Route::post('add-galery', function(Request $req){
        if($req->hasFile('file')){
            $date = date_create();$name= date_format($date, 'U-').str_random(50);
            $file=$req->file('file');
            $file->move( base_path().'/asset/uploads' , $name.".".$file->getClientOriginalExtension());
            if(Imagen::where('producto_id', $req->id)->get()){
                $position = intval(Imagen::where('producto_id', $req->id)->max('order_img'))+1;
            }else{
                $position = 0;
            }
            $imagen = new Imagen;
            $imagen->producto_id = $req->id;
            $imagen->order_img = $position;
            $imagen->picture='/asset/uploads/'.$name.".".$file->getClientOriginalExtension();
            $imagen->save();

            return response()->json($imagen);
        }
    });
    Route::post('delete-galery', function(Request $req){
        $img = Imagen::find($req->id);
        $img->delete();

        return response()->json(['id'=>$req->id]);
    });
    Route::get('positions-img', function(Request $request){
        $array = $request->datos;
        $array = explode(',',$array[0]);

        foreach ($array as $position => $item)
        {
            $promo = Imagen::find($item);
            $promo->order_img = $position;
            $promo->save();  
        }

        return response()->json(array('success'  => true ));
    });
    Route::get('productos/{type}/{id}', function($type, $id){
    
        if($type=="tipo" and $type!=" "){
            $data = TipoProducto::where('linea_negocio_id', $id)->orderBy('nombre', 'ASC')->pluck('nombre', 'id');
            $name = 'tipo_producto_id';
            $ids = 'tipos';
        }

        if($type=="marcas" and $type!=""){
            $data = Marca::where('tipo_producto_id', $id)->orderBy('nombre', 'ASC')->pluck('nombre', 'id')->toArray();
            $name = 'marcas_id';
            $ids = 'marcas';
        }

        if($type=="modelos" and $type!=" "){
            $data = Modelo::where('marcas_id', $id)->orderBy('nombre', 'ASC')->pluck('nombre', 'id')->toArray();
            $name = 'modelo_id';
            $ids = 'modelos';
        }

        $data[''] = "Seleccione una opción";
        return Form::select($name, $data, '', ['class'=>'form-control', 'id'=>$ids]);
    });
    Route::get('productos-filter/{type}/{id}', function($type, $id){
        $html = "<option class='visible' value='all'>Todos</option>";
        if($type=="tipo" and $type!=" "){
            $html = "<option class='visible' value='all'>Todos</option>";
            $data = TipoProducto::where('linea_negocio_id', $id)->orderBy('nombre', 'ASC')->get();
            foreach ($data as $value) {
                $html .= '<option value="'.$value->id.'" class="visible">'.$value->nombre.'</option>';
            }
        }

        if($type=="marcas" and $type!=""){
            $html = "<option class='visible' value='all'>Todas</option>";
            $data = Marca::where('tipo_producto_id', $id)->orderBy('nombre', 'ASC')->get();
            foreach ($data as $value) {
                $html .= '<option value="'.$value->id.'" class="visible">'.$value->nombre.'</option>';
            }
        }

        if($type=="modelos" and $type!=" "){
            $html = "<option class='visible' value='all'>Todos</option>";
            $data = Modelo::where('marcas_id', $id)->orderBy('nombre', 'ASC')->get();
            foreach ($data as $value) {
                $html .= '<option value="'.$value->id.'" class="visible">'.$value->nombre.'</option>';
            }
        }
        return $html;
    });
    Route::get('subir-cat', function(){
        $data = array('MARCA'=>'TIPO DE PRODUCTO',
        'AGL'=>'LASERS',
        'AERIAL LIFT INC.'=>'ELEVADOR TELESCÓPICO',
        'AIR BURNERS'=>'PALAS DE ÁRBOL',
        'AIRMAN'=>'COMPRESORES DE AIRE',
        'AIRMAN'=>'EXCAVADORAS',
        'AIRMAN'=>'PLANTAS DE LUZ',
        'AKERMAN'=>'EXCAVADORAS',
        'ALITEC'=>'ALL',
        'ALITEC'=>'CORTADORA DE CONCRETO',
        'ALITEC'=>'PAVIMENTADORA',
        'AL-JON'=>'EQUIPO FORESTAL',
        'ALLATT'=>'ALL',
        'ALLEY KAT'=>'MONTACARGAS',
        'ALLIANCE'=>'BOMBAS DE HORMIGON',
        'ALLIED'=>'COMPACTADOR',
        'ALLIED'=>'MARTILLO HIDRÁULICO',
        'ALLIED'=>'HERRAMIENTAS PERFORACION',
        'ALLIS CHALMERS'=>'ALL',
        'ALLIS CHALMERS'=>'QUEBRADORAS',
        'ALLMAND BROS'=>'ALL',
        'ALLTRACK'=>'TRACTOCAMION',
        'ALLU'=>'ALL',
        'ALTEC'=>'ALL',
        'ALTO'=>'BARREDORAS',
        'AMERAMAX'=>'COMPACTADORAS',
        'AMERICAN'=>'EXCAVADORAS',
        'AMERICAN'=>'GRUAS HIDRÁULICAS',
        'AMERICAN AUGERS'=>'PERFORADORAS',
        'AMERICAN JENBACH'=>'COMPRESORES DE AIRE',
        'AMERICAN STEEL WORKS'=>'COMPACTADOR',
        'AMERIQUIP'=>'ELEVADOR TELESCÓPICO, DE PLUMA, DE TIJERA',
        'AMERIQUIP'=>'ESPAREADORA DE SELLO',
        'AMIDA'=>'ALL',
        'AMMANN'=>'COMPACTADORES',
        'AMZ'=>'PAVIMENTADORA',
        'ARDCO'=>'PERFORADORAS',
        'ARIEL'=>'COMPRESORES DE AIRE',
        'ARROW MASTER'=>'MARTILLO HIDRÁULICO',
        'ASHLAND'=>'ESCREPAS/TRAILLAS',
        'ASHLAND'=>'CORTADORA ',
        'ASPHALT-ZIPPER'=>'PAVIMENTADORA',
        'ASPLUNDH'=>'ELEVADOR TELESCÓPICO',
        'ASPLUNDH'=>'ESPAREADORA DE SELLO',
        'ASTEC'=>'ALL',
        'ASTEC'=>'ZANJADORAS',
        'ASV POSITRACK'=>'TRACTOCAMION',
        'ASV POSITRACK'=>'MINICARGADORAS',
        'ATHEY'=>'MOTONIVELADORAS',
        'ATHEY'=>'PAVIMENTADORA',
        'ATHEY'=>'BARREDORAS',
        'ATLAS COPCO'=>'ALL',
        'ATLAS COPCO'=>'COMPRESORES DE AIRE',
        'ATLAS COPCO'=>'PERFORADORAS',
        'ATLAS COPCO'=>'MARTILLO HIDRÁULICO',
        'AUSTIN WESTERN'=>'RODILLOS',
        'AUSTIN WESTERN'=>'MOTONIVELADORAS',
        'AUSTIN WESTERN'=>'GRÚAS TODO TERRENO',
        'AUTO CRANE'=>'ALL',
        'B BL PEGSON'=>'ALL',
        'B P I'=>'MANIPULADOR TELESCÓPICO',
        'BADGER'=>'EXCAVADORAS',
        'BADGER'=>'GRÚAS TODO TERRENO',
        'BADGER'=>'GRÚAS DE CAMIONES',
        'BALDOR'=>'PLANTAS DE LUZ',
        'BALLYMORE'=>'ELEVADOR TELESCÓPICO',
        'BANDIT'=>'ESPAREADORA DE SELLO',
        'BANDIT'=>'EQUIPO FORESTAL',
        'BANDIT'=>'CORTADORAS',
        'BANTAM'=>'ALL',
        'BARBCO'=>'PERFORADORAS',
        'BARBER GREENE'=>'PAVIMENTADORA',
        'BARBER GREENE'=>'ZANJADORAS',
        'BARKO'=>'ALL',
        'BARKO'=>'FELLER BUNCHERS',
        'BASIC'=>'COMPACTADORES',
        'BASIC'=>'MOTONIVELADORAS',
        'BEARCAT'=>'ESPAREADORA DE SELLO',
        'BEARCAT'=>'PAVIMENTADORA',
        'BELL'=>'EQUIPO FORESTAL',
        'BELL'=>'TRACTOCAMION',
        'BELLE'=>'MINICARGADORAS',
        'BENATI'=>'REPARADORAS',
        'BENATI'=>'EXCAVADORAS',
        'BENFORD'=>'ALL',
        'BLAW KNOX'=>'PAVIMENTADORA',
        'BOBCAT'=>'COMPRESORES DE AIRE',
        'BOBCAT'=>'REPARADORAS',
        'BOBCAT'=>'ESPAREADORA DE SELLO',
        'BOBCAT'=>'COMPACTADORES',
        'BOBCAT'=>'CORTADORA DE CONCRETO',
        'BOBCAT'=>'BOMBAS DE HORMIGON',
        'BOBCAT'=>'PERFORADORAS',
        'BOBCAT'=>'EXCAVADORAS',
        'BOBCAT'=>'FELLER BUNCHERS',
        'BOBCAT'=>'MARTILLO HIDRÁULICO',
        'BOBCAT'=>'EQUIPO FORESTAL',
        'BOBCAT'=>'MOTONIVELADORAS',
        'BOBCAT'=>'PAVIMENTADORA',
        'BOBCAT'=>'MONTACARGAS',
        'BOBCAT'=>'CARGADORES',
        'BOBCAT'=>'MINICARGADORAS',
        'BOBCAT'=>'BARREDORAS',
        'BOBCAT'=>'MANIPULADOR TELESCÓPICO',
        'BOBCAT'=>'SIERRAS DE ÁRBOL',
        'BOBCAT'=>'CORTADORAS',
        'BOBCAT'=>'ZANJADORAS',
        'BOMAG'=>'COMPACTADORES',
        'BOMAG'=>'PAVIMENTADORA',
        'BOR-IT'=>'PERFORADORAS',
        'BOSS'=>'PLANTAS DE LUZ',
        'BOXER'=>'MINICARGADORAS',
        'BRADCO'=>'ZANJADORAS',
        'BROCE'=>'BARREDORAS',
        'BRODERSON'=>'GRÚAS HIDRÁULICAS',
        'BRODERSON'=>'MARTILLO HIDRÁULICO',
        'BRODERSON'=>'GRÚAS TODO TERRENO',
        'BROSS'=>'COMPACTADORES',
        'BROSS'=>'PAVIMENTADORA',
        'BROUWER'=>'MONTACARGAS',
        'BROWN'=>'EQUIPO FORESTAL',
        'BROWN'=>'SIERRAS DE ÁRBOL',
        'BUCKEYE'=>'ZANJADORAS',
        'BURKEEN'=>'ZANJADORAS',
        'BUSH-HOG'=>'PERFORADORAS',
        'C D S '=>'REPARADORAS',
        'C D S '=>'MONTACARGAS',
        'C D S '=>'CARGADORES',
        'C M E '=>'PERFORADORAS',
        'C M I'=>'COMPACTADORES',
        'C M I'=>'EQUIPO FORESTAL',
        'C M I'=>'MOTONIVELADORAS',
        'C M I'=>'PAVIMENTADORA',
        'C S I'=>'EQUIPO FORESTAL',
        'C S JOHNSON'=>'PLANTAS LOTES HORMIGÓN',
        'C S JOHNSON'=>'PAVIMENTADORA',
        'C T R'=>'DELIMBERS',
        'C T R'=>'FELLER BUNCHERS',
        'C T R'=>'EQUIPO FORESTAL',
        'C T R'=>'DESLIZADORAS',
        'CANNON'=>'PERFORADORAS',
        'CARE-LIFT'=>'MANIPULADOR TELESCÓPICO',
        'CARLSON'=>'PAVIMENTADORA',
        'CARLTON'=>'CORTADORAS',
        'CARVER'=>'BOMBAS ',
        'CASE'=>'REPARADORAS',
        'CASE'=>'COMPACTADORES',
        'CASE'=>'CARGADORES',
        'CASE'=>'PERFORADORAS',
        'CASE'=>'MOTORES',
        'CASE'=>'EXCAVADORAS',
        'CASE'=>'MOTONIVELADORAS',
        'CASE'=>'TRACTOCAMION',
        'CASE'=>'MONTACARGAS',
        'CASE'=>'GRÚAS TODO TERRENO',
        'CASE'=>'CARGADORES',
        'CASE'=>'MINICARGADORAS',
        'CASE'=>'GRÚAS',
        'CASE'=>'MANIPULADOR TELESCÓPICO',
        'CASE'=>'ZANJADORAS',
        'CATERPILLAR'=>'CATERPILLAR INDEX',
        'CEMCO'=>'PLANTAS LOTES HORMIGÓN',
        'CEMEN TECH'=>'PAVIMENTADORA',
        'CHAMBERS'=>'EQUIPO FORESTAL',
        'CHAMP'=>'ELEVADORES AEREOS',
        'CHAMP'=>'MONTACARGAS',
        'CHAMPION'=>'COMPACTADORES',
        ''=>'MOTONIVELADORAS',
        'CHICAGO PNEUMATIC'=>'COMPRESORES DE AIRE',
        ''=>'PERFORADORAS',
        'CIFA'=>'BOMBAS DE CONCRETO',
        'CLARK/LIMA'=>'GRÚAS TRACTOR',
        ''=>'GRÚAS HIDRÁULICAS',
        ''=>'GRÚAS TODO TERRENO',
        ''=>'GRÚAS DE CAMIONES',
        'CLEVELAND '=>'ZANJADORAS',
        'COMBILIFT'=>'MONTACARGAS',
        'COMMANDER'=>'MINICARGADORAS',
        'COMPAC'=>'COMPACTADORES',
        'CONDOR'=>'ELEVADOR TELESCÓPICO, DE PLUMA, DE TIJERA',
        'CON-E-CO'=>'PLANTAS LOTES HORMIGÓN',
        'COYOTE'=>'EXCAVADORAS',
        ''=>'CARGADORES',
        'CRABTREE'=>'ESCREPAS',
        'CRAFCO'=>'PAVIMENTADORA',
        'CUMMINS'=>'MOTORES',
        'CUMMINS'=>'PLANTAS DE LUZ',
        'CURBMASTER'=>'ALL',
        'D D T '=>'TRACTOCAMION',
        'DAEWOO/DOOSAN'=>'GRÚAS TRACTOR',
        'DAEWOO/DOOSAN'=>'EXCAVADORAS',
        'DAEWOO/DOOSAN'=>'INTEGRATED TOOL CARRIERS',
        'DAEWOO/DOOSAN'=>'CARGADORES DE REGISTROS',
        'DAEWOO/DOOSAN'=>'CARGADORES',
        'DAEWOO/DOOSAN'=>'MINICARGADORAS',
        'DAJNONG'=>'MARTILLO HIDRÁULICO',
        'DANDY-DIGGER'=>'PERFORADORAS',
        'DANUSER'=>'PERFORADORAS',
        'DANZCO'=>'DELIMBERS',
        'DART'=>'TRACTOCAMION',
        'DEERE'=>'REPARADORAS',
        'DEERE'=>'TRACTORES',
        'DEERE'=>'EXCAVADORAS',
        'DEERE'=>'FELLER BUNCHERS',
        'DEERE'=>'EXPEDIDORES',
        'DEERE'=>'INTEGRATED TOOL CARRIERS',
        'DEERE'=>'CARGADORES DE REGISTROS',
        'DEERE'=>'EQUIPO FORESTAL',
        'DEERE'=>'MOTONIVELADORAS',
        'DEERE'=>'TRACTOCAMION',
        'DEERE'=>'ESCREPAS',
        'DEERE'=>'MONTACARGAS',
        'DEERE'=>'CARGADORES',
        'DEERE'=>'RASPADORES',
        'DEERE'=>'MINICARGADORAS',
        'DEERE'=>'DESLIZADORAS',
        'DEERE'=>'MANIPULADOR TELESCÓPICO',
        'DEGELMAN'=>'MANIPULADOR TELESCÓPICO',
        'DELTA'=>'CABLE LAYERS',
        'DEMAG'=>'EXCAVADORAS',
        'DEMAG'=>'GRÚAS TODO TERRENO',
        'DEMAG'=>'GRÚAS DE CAMIONES',
        'DENIS CIMAF'=>'EQUIPO FORESTAL',
        'DENIS CIMAF'=>'SIERRAS DE ÁRBOL',
        'DETROIT-DIESEL'=>'ENGINES',
        'DETROIT-DIESEL'=>'PLANTAS DE LUZ',
        'DIAMOND'=>'EQUIPO FORESTAL',
        'DIAMOND'=>'JARDINERAS',
        'DIEDRICH'=>'PERFORADORAS',
        'DINGO'=>'MINICARGADORAS',
        'DITCH WITCH'=>'ALL',
        'DITCH WITCH'=>'ZANJADORAS',
        'DONKEY'=>'MONTACARGAS',
        'DRESSER'=>'REPARADORAS',
        'DRESSER'=>'TRACTORES',
        'DRESSER'=>'EXCAVADORAS',
        'DRESSER'=>'TRACTOCAMION',
        'DRESSER'=>'MONTACARGAS',
        'DRESSER'=>'CARGADORES',
        'DRESSER'=>'RASPADORES',
        'DRESSER'=>'MINICARGADORAS',
        'DRESSER'=>'TOPADOR DE RUEDAS',
        'DRESSTA'=>'TRACTORES',
        'DRESSTA'=>'CARGADORES',
        'DRILTECH'=>'PERFORADORAS',
        'DROTT'=>'EXCAVADORAS',
        'DROTT'=>'GRÚAS TODO TERRENO',
        'DUNHAM'=>'EQUIPO FORESTAL',
        'DURAPATCHER'=>'PAVIMENTADORA',
        'DURATECH'=>'ALL',
        'DYMAX'=>'ALL',
        'DYNAHOE'=>'REPARADORAS',
        'DYNAPAC'=>'COMPACTADORES',
        'DYNAPAC'=>'PAVIMENTADORA',
        'EAGLE CRUSHER'=>'TRITURADORAS',
        'EAGLE IRON WORKS'=>'TRITURADORAS',
        'EAGLE-PICHER'=>'MONTACARGAS',
        'EARTHFORCE'=>'REPARADORAS',
        'EASI-POUR'=>'PAVIMENTADORA',
        'EASY LAWN'=>'ALL',
        'ECONOMY'=>'ELEVADOR TELESCÓPICO, DE PLUMA, DE TIJERA',
        'ELGIN'=>'BARREDORAS',
        'EL-JAY'=>'TRITURADORAS',
        'ELLIOTT'=>'GRÚAS DE CAMIONES',
        'ENTEK'=>'COMPACTADORES',
        'ESCO'=>'MARTILLO HIDRÁULICO',
        'ESSICK'=>'ALL',
        'ETNYRE'=>'PAVIMENTADORA',
        'EUCLID-HITACHI'=>'ALL',
        'EXTEC'=>'ALL',
        'EZ-SCREEN'=>'TRITURADORAS',
        'F E C'=>'DELIMBERS',
        'F E C'=>'EQUIPO FORESTAL',
        'F M C'=>'BARREDORAS',
        'FABTEC'=>'ALL',
        'FAILING'=>'PERFORADORAS',
        'FASSI'=>'GRÚAS DE CAMIONES',
        'FECON'=>'ALL',
        'FERGUSON'=>'COMPACTADORES',
        'FERMEC'=>'ALL',
        'FIATALLIS'=>'REPARADORAS',
        'FIATALLIS'=>'TRACTORES',
        'FIATALLIS'=>'EXCAVADORAS',
        'FIATALLIS'=>'MOTONIVELADORAS',
        'FIATALLIS'=>'CARGADORES',
        'FIATALLIS'=>'ESCREPAS',
        'FINLAY'=>'ALL',
        'FINN'=>'MINICARGADORAS',
        'FINTEC'=>'TRITURADORAS',
        'FLAHERTY'=>'PAVIMENTADORA',
        'FOREMOST'=>'ALL',
        'FOX PRODUCTS'=>'REPARADORAS',
        'FOX PRODUCTS'=>'ESCREPAS',
        'FRANKLIN'=>'CARGADORES',
        'FRANKLIN'=>'EQUIPO FORESTAL',
        'FUCHS'=>'EXCAVADORAS',
        'FURUKAWA'=>'TRACTORES',
        'FURUKAWA'=>'PERFORADORAS',
        'FURUKAWA'=>'CARGADORES',
        'GAFNER'=>'ALL',
        'GAFNER'=>'REPARADORAS',
        'GAFNER'=>'DESLIZADORAS',
        'GALION'=>'COMPACTADORES',
        'GALION'=>'MOTONIVELADORAS',
        'GALION'=>'PAVIMENTADORA',
        'GALION'=>'GRÚAS TODO TERRENO',
        'GARDNER-DENVER'=>'COMPRESORES DE AIRE',
        'GARDNER-DENVER'=>'PERFORADORAS',
        'GARFIELD'=>'ESCREPAS',
        'GEARMORE'=>'PERFORADORAS',
        'GEFCO'=>'PERFORADORAS',
        'GEHL'=>'COMPACTADORES',
        'GEHL'=>'EXCAVADORAS',
        'GEHL'=>'MARTILLO HIDRÁULICO',
        'GEHL'=>'MOTONIVELADORAS',
        'GEHL'=>'PAVIMENTADORA',
        'GEHL'=>'CARGADORES',
        'GEHL'=>'MINICARGADORAS',
        'GEHL'=>'MANIPULADOR TELESCÓPICO',
        'GENERAC'=>'PLANTAS DE LUZ',
        'GENIE'=>'ALL',
        'GENIE'=>'ELEVADOR TELESCÓPICO, DE PLUMA, DE TIJERA',
        'GENIE'=>'PLANTAS DE LUZ',
        'GENIE'=>'MANIPULADOR TELESCÓPICO',
        'GEOPROBE'=>'ALL',
        'GOMACO'=>'ALL',
        'GOMACO'=>'PAVIMENTADORA',
        'GOOSSEN'=>'ESPAREADORA DE SELLO',
        'GORMAN-RUPP'=>'BOMBAS',
        'GRACE'=>'COMPACTADORES',
        'GRACE'=>'PAVIMENTADORA',
        'GRACE'=>'BARREDORAS',
        'GRADALL'=>'ALL',
        'GRADALL'=>'EXCAVADORAS',
        'GRADALL'=>'MONTACARGAS',
        'GRADALL'=>'MANIPULADOR TELESCÓPICO',
        'GRASAN'=>'ALL',
        'GRAVELY (ARIENS)'=>'ESPAREADORA DE SELLO',
        'GRIMMER-SCHMIDT'=>'COMPRESORES DE AIRE',
        'GROVE'=>'MANIPULADOR TELESCÓPICO',
        'GROVE'=>'GRÚAS HIDRAÚLICAS',
        'GROVE'=>'GRÚAS TODO TERRENO',
        'GRUENDLER'=>'TRIRURADORAS',
        'GYRO-TRAC'=>'ALL',
        'H E M '=>'PAVIMENTADORA',
        'HAHN'=>'EQUIPO FORESTAL',
        'HALLA'=>'EXCAVADORAS',
        'HALLA'=>'CARGADOR FRONTAL',
        'HALLA'=>'CARGADOR SOBRE NEUMÁTICOS',
        'HAMM'=>'ALL',
        'HAMM'=>'COMPACTADOR',
        'HAMM'=>'PAVIMENTADORA',
        'HANIX'=>'EXCAVADORAS',
        'HARLO'=>'MONTACARGAS',
        'HAULOTTE'=>'ELEVADOR TELESCÓPICO, DE PLUMA, DE TIJERA',
        'HAYBUSTER'=>'ALL',
        'HAZEMAG'=>'TRITURADORAS',
        'HELTZEL'=>'PAVIMENTADORA',
        'HESSTON'=>'MINICARGADORAS',
        'HEWITT-ROBINS'=>'ALL',
        'HEWITT-ROBINS'=>'TRANSPORTADORES',
        'HEWITT-ROBINS'=>'TRITURADORAS',
        'HIAB'=>'GRÚAS DE CAMIONES',
        'HITACHI'=>'GRÚAS DE TRACTOR',
        'HITACHI'=>'EXCAVADORAS',
        'HITACHI'=>'TRACTOCAMION',
        'HITACHI'=>'PALAS',
        'HOGZILA'=>'TUB GRINDERS',
        'HOIST'=>'ALL',
        'HONDA'=>'PLANTAS DE LUZ',
        'HOOD'=>'CARGADORES DE REGISTROS',
        'HOOD'=>'EQUIPO FORESTAL',
        'HOUGH'=>'ALL',
        'HUBER'=>'COMPACTADORES',
        'HUBER'=>'MOTONIVELADORAS',
        'HUMDINGER'=>'ESCREPAS',
        'HUSKY'=>'ALL',
        'HUSKY'=>'LOG LOADERS',
        'HYDRA MAC'=>'MINICARGADORAS',
        'HYDRA-MAXX'=>'ZANJADORAS',
        'HYPAC'=>'ALL',
        'HYPAC'=>'COMPACTADORES',
        'HYSTER'=>'ALL',
        'HYUNDAI'=>'ALL',
        'HYUNDAI'=>'EXCAVADORAS',
        'HYUNDAI'=>'INTEGRATED TOOL CARRIERS',
        'HYUNDAI'=>'CARGADORES',
        'I C C'=>'ALL',
        'I H I'=>'EXCAVADORAS',
        'I H I'=>'TRACTOCAMION',
        'I H I'=>'MINICARGADORAS',
        'I M T'=>'GRÚAS DE CAMIONES',
        'I M T INTERNATIONAL'=>'PERFORADORAS',
        'I P C'=>'MARTILLO HIDRÁULICO',
        'ICON'=>'MOTONIVELADORAS',
        'ICON'=>'ESCREPAS',
        'INDECO'=>'COMPACTADORES',
        'INDECO'=>'MARTILLO HIDRÁULICO',
        'INERTIA'=>'TRITURADORAS',
        'INGERSOLL RAND'=>'ALL',
        'INGERSOLL RAND'=>'COMPRESORES DE AIRE',
        'INGERSOLL RAND'=>'REPARADORAS',
        'INGERSOLL RAND'=>'COMPACTADORES',
        'INGERSOLL RAND'=>'PERFORADORA DIRECCIONAL',
        'INGERSOLL RAND'=>'PERFORADORAS',
        'INGERSOLL RAND'=>'PLANTAS DE LUZ',
        'INGERSOLL RAND'=>'PAVIMENTADORA',
        'INGERSOLL RAND'=>'MONTACARGAS',
        'INGERSOLL RAND'=>'MANIPULADOR TELESCÓPICO',
        'INGRAM'=>'ALL',
        'INNOVATOR'=>'ALL',
        'INSLEY'=>'EXCAVADORAS',
        'INTENSUS'=>'COMPACTADORES',
        'INTER-DRAIN'=>'ZANJADORAS',
        'INTERNATIONAL'=>'ALL',
        'J C B'=>'ALL',
        'J C B'=>'REPARADORAS',
        'J C B'=>'EXCAVADORAS',
        'J C B'=>'MARTILLO HIDRÁULICO',
        'J C B'=>'INTEGRATED TOOL CARRIERS',
        'J C B'=>'TRACTOCAMION',
        'J C B'=>'MONTACARGAS',
        'J C B'=>'CARGADORES',
        'J C B'=>'MINICARGADORAS',
        'J C B'=>'MANIPULADOR TELESCÓPICO',
        'J C B VIBROMAX'=>'ALL',
        'J C I'=>'ALL',
        'J L G'=>'ELEVADORES TELESCÓPICO',
        'J L G'=>'MANIPULADOR TELESCÓPICO',
        'J S W'=>'EXCAVADORAS',
        'JEWELL'=>'GRAPPLES',
        'JH FLETCHER'=>'EQUIPO DE MINERÍA',
        'JOHN HENRY'=>'PERFORADORAS',
        'JOY'=>'COMPRESORES DE AIRE',
        'JOY'=>'PERFORADORAS',
        'K D MANITOU'=>'ALL',
        'K P I'=>'TRITURADORAS',
        'KALMAR'=>'MONTACARGAS',
        'KATO'=>'EXCAVADORAS',
        'KAWASAKI'=>'INTEGRATED TOOL CARRIERS',
        'KAWASAKI'=>'CARGADORES',
        'KENDALL'=>'EQUIPO FORESTAL',
        'KENT'=>'COMPACTADORES',
        'KENT'=>'MARTILLO HIDRÁULICO',
        'KERSHAW'=>'ALL',
        'KESMAC'=>'MONTACARGAS',
        'KLEIN'=>'ALL',
        'KOBELCO'=>'REPARADORAS',
        'KOBELCO'=>'GRÚAS TRACTOR',
        'KOBELCO'=>'EXCAVADORAS',
        'KOBELCO'=>'CARGADORES',
        'KOEHRING'=>'ALL',
        'KOEHRING'=>'GRÚAS TRACTOR',
        'KOEHRING'=>'EXCAVADORAS',
        'KOEHRING'=>'EQUIPO FORESTAL',
        'KOEHRING'=>'GRÚAS TODO TERRENO',
        'KOEHRING'=>'ZANJADORAS',
        'KOEHRING'=>'GRÚAS DE CAMIONES',
        'KOHLER'=>'PLANTAS DE LUZ',
        'KOLBERG'=>'ALL',
        'KOLMAN'=>'ALL',
        'KOMATSU'=>'REPARADORAS',
        'KOMATSU'=>'COMPACTADORES',
        'KOMATSU'=>'TRACTORES',
        'KOMATSU'=>'TRITURADORAS',
        'KOMATSU'=>'EXCAVADORAS',
        'KOMATSU'=>'FELLER BUNCHERS',
        'KOMATSU'=>'FORWARDERS',
        'KOMATSU'=>'INTEGRATED TOOL CARRIERS',
        'KOMATSU'=>'EQUIPO FORESTAL',
        'KOMATSU'=>'MOTONIVELADORAS',
        'KOMATSU'=>'TRACTOCAMION',
        'KOMATSU'=>'CARGADORES',
        'KOMATSU'=>'ESCREPAS',
        'KOMATSU'=>'MINICARGADORAS',
        'KOMATSU'=>'TOPADOR DE RUEDAS',
        'KRAMER'=>'CARGADORES',
        'KRUPP'=>'GRÚAS TODO TERRENO',
        'K-TEC'=>'ESCREPAS',
        'KUBOTA'=>'REPARADORAS',
        'KUBOTA'=>'PERFORADORAS',
        'KUBOTA'=>'EXCAVADORAS',
        'KUBOTA'=>'PLANTAS DE LUZ',
        'KUBOTA'=>'MARTILLO HIDRÁULICO',
        'KUBOTA'=>'CARGADORES',
        'KUBOTA'=>'REPARADORAS',
        'KUBOTA'=>'ZANJADORAS',
        'L M C'=>'MINICARGADORAS',
        'LABOUNTY'=>'DEMOLITION GRAPPLES',
        'LABOUNTY'=>'DEMOLITION SHEARS',
        'LABOUNTY'=>'MARTILLO HIDRÁULICO',
        'LANEY'=>'PERFORADORAS ',
        'LASER-ALIGN'=>'LASERS',
        'LAY-MOR'=>'ALL',
        'LAYTON'=>'COMPACTADORES',
        'LAYTON'=>'PAVIMENTADORA',
        'LB-SMITH'=>'TRANSPORTADORES',
        'LEE'=>'MOTONIVELADORAS',
        'LEE BOY'=>'COMPACTADORES',
        'LEE BOY'=>'MOTONIVELADORAS',
        'LEE BOY'=>'PAVIMENTADORA',
        'LEMCO'=>'ALL',
        'LEROI'=>'COMPRESORES DE AIRE',
        'LETOURNEAU'=>'CARGADORES',
        'LEVCO'=>'TREE SPADES & STUMP CUTTERS',
        'LIEBHERR'=>'TRACTORES',
        'LIEBHERR'=>'EXCAVADORAS',
        'LIEBHERR'=>'TRACTOCAMION',
        'LIEBHERR'=>'GRÚAS TODO TERRENO',
        'LIEBHERR'=>'CARGADORES',
        'LIFTALL'=>'MONTACARGAS',
        'LIFTKING'=>'MONTACARGAS',
        'LIMA'=>'ALL',
        'LINCOLN'=>'PAVIMENTADORA',
        'LINCOLN'=>'SOLDADORAS',
        'LINDE'=>'MONTACARGAS',
        'LINDSAY'=>'COMPRESORES DE AIRE',
        'LINK BELT'=>'ALL',
        'LINK BELT'=>'GRÚAS TRACTOR',
        'LINK BELT'=>'EXCAVADORAS',
        'LINK BELT'=>'TRACTOCAMION',
        'LINK BELT'=>'GRÚAS TODO TERRENO',
        'LINK BELT'=>'GRÚAS DE CAMIONES',
        'LIPPMANN'=>'TRITURADORAS',
        'LITTLE GIANT CO.'=>'BARREDORAS',
        'LITTLE GIANT CRANE'=>'ALL',
        'LITTLEFORD'=>'PAVIMENTADORA',
        'LOAD LIFTER'=>'MONTACARGAS',
        'LODI'=>'REPARADORAS',
        'LORAIN'=>'ALL',
        'LORAIN'=>'GRÚAS TODO TERRENO',
        'LORAIN'=>'GRÚAS DE CAMIONES',
        'LULL'=>'MONTACARGAS',
        'LULL'=>'MANIPULADOR TELESCÓPICO',
        'LUXAR'=>'LASERS',
        'M - B COMPANY'=>'ESPAREADORA DE SELLO',
        'M - B COMPANY'=>'TRANSPORTADORES',
        'M - B COMPANY'=>'PAVIMENTADORA',
        'M - B COMPANY'=>'BARREDORAS',
        'M B W'=>'PAVIMENTADORA',
        'M E C'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'M E C'=>'MANIPULADOR TELESCÓPICO',
        'M M D'=>'PLANTAS DE LUZ',
        'MACLIFT'=>'MONTACARGAS',
        'MADILL'=>'FELLER BUNCHERS',
        'MADILL'=>'CARGADORES DE REGISTROS',
        'MADILL'=>'JARDINERAS',
        'MAGNATRAC-C F STRUCK'=>'TRACTORES',
        'MAGNUM'=>'PLANTAS DE LUZ',
        'MAGNUM'=>'MARTILLO HIDRÁULICO',
        'MAGNUM'=>'EQUIPO FORESTAL',
        'MANDIG'=>'REPARADORAS',
        'MANITEX'=>'GRÚAS DE CAMIONES',
        'MANITOU'=>'MONTACARGAS',
        'MANITOU'=>'MANIPULADOR TELESCÓPICO',
        'MONITOWOC'=>'GRÚAS TRACTOR',
        'MANITOWOC'=>'GRÚAS DE CAMIONES',
        'MANTIS'=>'GRÚAS TRACTOR',
        'MARATHON'=>'PLANTAS DE LUZ',
        'MARATHON LETOURNEAU'=>'TRITURADORAS',
        'MARATHON LETOURNEAU'=>'GRÚAS HIDRÁULICAS',
        'MARATHON LETOURNEAU'=>'EQUIPO FORESTAL',
        'MARATHON LETOURNEAU'=>'TRACTOCAMION',
        'MARATHON LETOURNEAU'=>'CARGADORES',
        'MARATHON LETOURNEAU'=>'GRÚAS',
        'MARATHON LETOURNEAU'=>'TOPADOR DE RUEDAS',
        'MARKLIFT'=>'ALL',
        'MARKLIFT'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'MARKLIFT'=>'MANIPULADOR TELESCÓPICO',
        'MARLOW'=>'BOMBAS',
        'MASABA'=>'ALL',
        'MASSEY FERGUSON'=>'ALL',
        'MASSEY FERGUSON'=>'REPARADORAS',
        'MASSEY FERGUSON'=>'TRACTORES',
        'MASSEY FERGUSON'=>'EXCAVADORAS',
        'MASSEY FERGUSON'=>'MONTACARGAS',
        'MASSEY FERGUSON'=>'CARGADORES',
        'MASSEY FERGUSON'=>'MINICARGADORAS',
        'MASSEY FERGUSON'=>'DESLIZADORAS',
        'MASTERCRAFT'=>'MONTACARGAS',
        'MASTERSKREEN'=>'TRITURADORAS',
        'MAULDIN'=>'ALL',
        'MAXIMAL'=>'MONTACARGAS',
        'MAXON'=>'ZANJADORAS',
        'MAYCO'=>'BOMBAS DE CONCRETO',
        'MCCLOSKEY'=>'TRITURADORAS',
        'MCLAUGHLIN'=>'PERFORADORA DIRECCIONAL',
        'MCPHERSON'=>'EQUIPO FORESTAL',
        'MEGA'=>'ALL',
        'MELTRAC'=>'MINICARGADORAS',
        'MENSCH'=>'ESCREPAS',
        'MENZI MUCK'=>'EXCAVADORAS',
        'MICHIGAN'=>'ALL',
        'MICHIGAN'=>'REPARADORAS',
        'MICHIGAN'=>'CARGADORES',
        'MICHIGAN'=>'ESCREPAS',
        'MICHIGAN'=>'TOPADOR DE RUEDAS',
        'MIDLAND'=>'PAVIMENTADORA',
        'MIDMARK'=>'ZANJADORAS',
        'MIKASA'=>'COMPACTADORES',
        'MILLER'=>'SOLDADORAS',
        'MILLER FORMLESS'=>'ALL',
        'MILLER FORMLESS'=>'PAVIMENTADORA',
        'MILLER SPREADER'=>'PAVIMENTADORA',
        'MINUTEMAN'=>'BARREDORAS',
        'MISKIN'=>'ESCREPAS',
        'MITSUBISHI'=>'TRACTORES',
        'MITSUBISHI'=>'EXCAVADORAS',
        'MITSUBISHI'=>'MOTONIVELADORAS',
        'MITSUBISHI'=>'CARGADORES',
        'MOBIL SWEEPER'=>'BARREDORAS',
        'MOBILE DRILL CO.'=>'PERFORADORAS',
        'MOFFETT'=>'MONTACARGAS',
        'MORBARK'=>'ALL',
        'MORBARK'=>'CHIP HARVESTERS',
        'MORBARK'=>'FELLER BUNCHERS',
        'MORBARK'=>'GRAPPLES',
        'MORBARK'=>'LOG LOADERS',
        'MORBARK'=>'EQUIPO FORESTAL',
        'MORBARK'=>'SIERRAS DE ÁRBOL',
        'MORBARK'=>'TUB GRINDERS',
        'MORGEN'=>'BOMBAS DE CONCRETO',
        'MORROKA'=>'TRACTOCAMION',
        'MOXY'=>'TRACTOCAMION',
        'MR-AIR'=>'BARREDORAS',
        'MULLER'=>'COMPACTADORES',
        'MULTIQUIP'=>'COMPACTADORES',
        'MULTIQUIP'=>'PLANTAS DE LUZ',
        'MUSTANG'=>'PERFORADORAS',
        'MUSTANG'=>'EXCAVADORAS',
        'MUSTANG'=>'MARTILLO HIDRÁULICO',
        'MUSTANG'=>'PAVIMENTADORA',
        'MUSTANG'=>'CARGADORES',
        'MUSTANG'=>'MINICARGADORAS',
        'MUSTANG'=>'BARREDORAS',
        'MUSTANG'=>'MANIPULADOR TELESCÓPICO',
        'N P K '=>'COMPACTADORES',
        'N P K '=>'MARTILLO HIDRÁULICO',
        'NAGANO'=>'EXCAVADORAS',
        'N-AMERICAN'=>'COMPACTADORES',
        'NASCO'=>'MONTACARGAS',
        'NATIONAL'=>'GRÚAS HIDRAÚLICAS',
        'NAVIGATOR'=>'MONTACARGAS',
        'NEAL'=>'COMPACTADORES',
        'NEAL'=>'PAVIMENTADORA',
        'NEW HOLLAND / FORD'=>'REPARADORAS',
        'NEW HOLLAND / FORD'=>'TRACTORES',
        'NEW HOLLAND / FORD'=>'PERFORADORAS',
        'NEW HOLLAND / FORD'=>'EXCAVADORAS',
        'NEW HOLLAND / FORD'=>'INTEGRATED TOOL CARRIERS',
        'NEW HOLLAND / FORD'=>'MOTONIVELADORAS',
        'NEW HOLLAND / FORD'=>'TRACTOCAMION',
        'NEW HOLLAND / FORD'=>'CARGADORES',
        'NEW HOLLAND / FORD'=>'MINICARGADORAS',
        'NEW HOLLAND / FORD'=>'MANIPULADOR TELESCÓPICO',
        'NISSAN'=>'EXCAVADORAS',
        'NITE-HAWK'=>'BARREDORAS',
        'NOBLE'=>'ESCREPAS',
        'NOBLE'=>'MONTACARGAS',
        'NOBLES'=>'BARREDORAS',
        'NORAM'=>'PLANTAS DE LUZ',
        'NORAM'=>'MOTONIVELADORAS',
        'NORDBERG'=>'TRANSPORTADORES',
        'NORDBERG'=>'TRITURADORAS',
        'NORKOT'=>'TUB GRINDERS',
        'NORSTAR'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'NORTHWEST'=>'ALL',
        'O & K TROJAN'=>'TRACTOCAMION',
        'O & K TROJAN'=>'GRÚAS TODO TERRENO',
        'O & K TROJAN'=>'CARGADORES',
        'O M C'=>'CARGADORES',
        'O M C'=>'MINICARGADORAS',
        'OKADA'=>'COMPACTADORES',
        'OKADA'=>'MARTILLO HIDRÁULICO',
        'OLATHE'=>'ESPAREADORA DE SELLO',
        'OLATHE'=>'TUB GRINDERS',
        'OLIN'=>'BOMBAS DE CONCRETO',
        'OLIVER'=>'TRACTORES',
        'OLIVER'=>'MONTACARGAS',
        'OLYMPIAN'=>'PLANTAS DE LUZ',
        'ONAN'=>'PLANTAS DE LUZ',
        'P & H'=>'ALL',
        'P & H'=>'GRÚAS TODO TERRENO',
        'P E P'=>'TRITURADORAS',
        'P M'=>'GRÚAS DE CAMIONES',
        'P S I'=>'MOTONIVELADORAS',
        'PALFINGER'=>'ALL',
        'PALFINGER'=>'MONTACARGAS',
        'PALM'=>'COMPACTADORES',
        'PALM'=>'MOTONIVELADORAS',
        'PAYHAULER'=>'TRACTOCAMION',
        'PEERLESS'=>'TRITURADORAS',
        'PEERLESS'=>'LOG LOADERS',
        'PETERSON'=>'DELIMBERS',
        'PETERSON'=>'EQUIPO FORESTAL',
        'PETTIBONE MICHIGAN'=>'COMPACTADORES',
        'PETTIBONE MICHIGAN'=>'GRÚAS HIDRAÚLICAS',
        'PETTIBONE MICHIGAN'=>'MONTACARGAS',
        'PETTIBONE MICHIGAN'=>'GRÚAS TODO TERRENO',
        'PETTIBONE MICHIGAN'=>'DESLIZADORAS',
        'PETTIBONE MICHIGAN'=>'MANIPULADOR TELESCÓPICO',
        'PIERCE'=>'DELIMBERS',
        'PIERCE'=>'GRAPPLES',
        'PIONEER'=>'TRITURADORAS',
        'PIONEER'=>'GRÚAS DE CAMIONES',
        'PK MFG'=>'PAVIMENTADORA',
        'POCLAIN'=>'EXCAVADORAS',
        'POLARIS'=>'MINICARGADORAS',
        'PONSSE'=>'EQUIPO FORESTAL',
        'PORTEC'=>'TRITURADORAS',
        'PORTEC'=>'TUB GRINDERS',
        'POTAIN'=>'GRÚAS HIDRAÚLICAS',
        'POWER CURBERS'=>'ALL',
        'POWER PAVERS'=>'PAVIMENTADORA',
        'POWER TRAC'=>'REPARADORAS',
        'POWER-BOSS'=>'BARREDORAS',
        'POWERSCREEN'=>'TRANSPORTADORES',
        'POWERSCREEN'=>'TRITURADORAS',
        'PRECISION HUSKY'=>'ALL',
        'PRENTICE'=>'FELLER BUNCHERS',
        'PRENTICE'=>'FORWARDERS',
        'PRENTICE'=>'LOG LOADERS',
        'PRENTICE'=>'EQUIPO FORESTAL',
        'PRENTICE'=>'DESLIZADORAS',
        'PRENTICE'=>'GRÚAS DE CAMIONES',
        'PRIME'=>'ESCREPAS',
        'PRIME MOVER'=>'PAVIMENTADORA',
        'PRIME MOVER'=>'CARGADORES',
        'PRIME MOVER'=>'MINICARGADORAS',
        'PRINCETON'=>'MONTACARGAS',
        'PRO PAV'=>'PAVIMENTADORA',
        'PROPAVER'=>'PAVIMENTADORA',
        'PUCKETT'=>'ALL',
        'PUTZMEISTER'=>'BOMBAS DE CONCRETO',
        'QUALCOMM'=>'SISTEMAS POSICIÓN GLOBAL',
        'QUINCY'=>'COMPRESORES DE AIRE',
        'R C E'=>'EXCAVADORAS',
        'R O CORPORATION'=>'GRÚAS DE CAMIONES',
        'RAMEY'=>'LOG LOADERS',
        'RAMMAX'=>'COMPACTADORES',
        'RAMMER'=>'MARTILLO HIDRÁULICO',
        'RAMROD'=>'MINICARGADORAS',
        'RANDON'=>'TRACTOCAMION',
        'RANGER'=>'DESLIZADORAS',
        'RAYCO'=>'EQUIPO FORESTAL',
        'RAYGO'=>'COMPACTADORES',
        'RAYGO'=>'PAVIMENTADORA',
        'REACHMASTER'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'READ'=>'TRITURADORAS',
        'READ'=>'TUB GRINDERS',
        'REED MFG. CO.'=>'BOMBAS DE CONCRETO',
        'REXNORD INC.'=>'ALL',
        'REXWORKS'=>'COMPACTADORES',
        'REXWORKS'=>'LOTES DE CONCRETO',
        'REXWORKS'=>'PAVIMENTADORA',
        'REXWORKS'=>'TUB GRINDERS',
        'REYNOLDS INTL.'=>'ESCREPAS',
        'RHINO'=>'PERFORADORAS',
        'RIG WORKS'=>'PERFORADORAS',
        'RILEY'=>'DELIMBERS',
        'RISLEY'=>'EQUIPO FORESTAL',
        'ROADTEC'=>'PAVIMENTADORA',
        'ROL-MOL'=>'COMPACTADORES',
        'ROME'=>'ESCREPAS',
        'ROSCO'=>'ALL',
        'ROSCO'=>'COMPACTADORES',
        'ROSS'=>'LOTES DE CONCRETO',
        'ROTOBEC'=>'ALL',
        'ROTOBEC'=>'FORWARDERS',
        'ROTOCHOPPER'=>'ALL',
        'ROTTNE'=>'FORWARDERS',
        'ROW-KING'=>'EQUIPO FORESTAL',
        'ROYAL'=>'MONTACARGAS',
        'ROYER'=>'TRITURADORAS',
        'S E M'=>'COMPACTADORES',
        'S E M'=>'TOPADOR DE RUEDAS',
        'S E M'=>'TRACTORES',
        'S E M'=>'MOTONIVELADORAS',
        'S E M'=>'CARGADORES',
        'SABINE'=>'PAVIMENTADORA',
        'SAKAI'=>'COMPACTADORES',
        'SALSCO'=>'ALL',
        'SAMSUNG'=>'TRACTORES',
        'SAMSUNG'=>'EXCAVADORAS',
        'SAMSUNG'=>'INTEGRATED TOOL CARRIERS',
        'SAMSUNG'=>'CARGADORES',
        'SANDVIK'=>'TRITURADORAS',
        'SANDVIK'=>'PERFORADORAS',
        'SANY'=>'ALL',
        'SCAT TRAK'=>'ALL',
        'SCAT TRAK'=>'EXCAVADORAS',
        'SCAT TRAK'=>'CARGADORES',
        'SCAT TRAK'=>'MINICARGADORAS',
        'SCHAEFF'=>'EXCAVADORAS',
        'SCHAEFF'=>'CARGADORES',
        'SCHRAMM'=>'PERFORADORAS',
        'SCHWING'=>'BOMBAS DE CONCRETO',
        'SCOOPMOBILE'=>'ALL',
        'SCOOPMOBILE'=>'CARGADORES',
        'SCOTT ATO'=>'GRÚAS HIDRAÚLICAS',
        'SCREEN MACHINE'=>'ALL',
        'SCREEN USA'=>'TRITURADORAS',
        'SDLG-RANGER'=>'CARGADORES',
        'SENNEBOGEN'=>'EXCAVADORAS',
        'SERCO'=>'LOG LOADERS',
        'SHUTTLELIFT'=>'GRÚAS TODO TERRENO',
        'SKY JACK'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'SKY JACK'=>'MANIPULADOR TELESCÓPICO',
        'SKYTRACK'=>'MANIPULADOR TELESCÓPICO',
        'SMITH'=>'COMPRESORES DE AIRE',
        'SNORKEL'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'SOILMEC'=>'PERFORADORAS',
        'SPAULDING'=>'TRITURADORAS',
        'SPECTRA PRECISION'=>'LASERS',
        'SPECTRA-PHYSICS'=>'SISTEMAS POSICIÓN GLOBAL',
        'SPECTRA-PHYSICS'=>'LASERS',
        'SPEICHER'=>'ZANJADORAS',
        'STANLEY'=>'COMPACTADORES',
        'STANLEY'=>'MARTILLO HIDRÁULICO',
        'STEPHENS'=>'LOTES DE CONCRETO',
        'STONE'=>'COMPACTADORES',
        'STOW MANUFACTURING'=>'ALL',
        'STRAIGHTLINE'=>'PERFORADORA DIRECCIONAL',
        'STRATO LIFT'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'STUMPSTER'=>'CORTADORAS',
        'SULLAIR CORPORATION'=>'COMPRESORES DE AIRE',
        'SULLIVAN'=>'ALL',
        'SULLIVAN'=>'COMPRESORES DE AIRE',
        'SULLIVAN'=>'PERFORADORAS',
        'SUPERIOR BROOM'=>'BARREDORAS',
        'SUPERPAC'=>'COMPACTADORES',
        'SUPERTRAK'=>'COMPACTADORES',
        'SWEEPRITE'=>'BARREDORAS',
        'SWEEPSTER'=>'ALL',
        'SWEEPSTER'=>'BARREDORAS',
        'SWINGER'=>'CARGADORES',
        'T C I'=>'ALL',
        'T C I'=>'MONTACARGAS',
        'T C I'=>'CARGADORES',
        'T C M'=>'CARGADORES',
        'T.L. SMITH'=>'PAVIMENTADORA',
        'TADANO'=>'GRÚAS TODO TERRENO',
        'TADANO'=>'GRÚAS DE CAMIONES',
        'TAILIFT'=>'MONTACARGAS',
        'TAKEUCHI'=>'EXCAVADORAS',
        'TAKEUCHI'=>'CARGADORES',
        'TAKEUCHI'=>'MINICARGADORAS',
        'TAMPO'=>'ALL',
        'TAMROCK'=>'PERFORADORAS',
        'TAYLOR'=>'MONTACARGAS',
        'TECO'=>'ALL',
        'TELEDYNE'=>'MARTILLO HIDRÁULICO',
        'TELELECT'=>'PERFORADORAS',
        'TELESTACK'=>'TRITURADORAS',
        'TELSMITH'=>'TRITURADORAS',
        'TENNANT'=>'BARREDORAS',
        'TEREX'=>'ALL',
        'TEREX'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'TEREX'=>'REPARADORAS',
        'TEREX'=>'COMPACTADORES',
        'TEREX'=>'TRACTORES',
        'TEREX'=>'EXCAVADORAS',
        'TEREX'=>'PLANTAS DE LUZ',
        'TEREX'=>'TRACTOCAMION',
        'TEREX'=>'GRÚAS TODO TERRENO',
        'TEREX'=>'CARGADORES',
        'TEREX'=>'ESCREPAS',
        'TEREX'=>'MINICARGADORAS',
        'TEREX'=>'MANIPULADOR TELESCÓPICO',
        'TEREX'=>'GRÚAS DE CAMIONES',
        'TEREX CANICA'=>'TRITURADORAS',
        'TEREX CEDARAPIDS'=>'TRITURADORAS',
        'TEREX DEMAG'=>'GRÚAS TODO TERRENO',
        'TEREX FINLAY'=>'TRITURADORAS',
        'TEREX PEGSON'=>'TRITURADORAS',
        'TEREX UNIT RIG'=>'TRACTOCAMION',
        'TERRAMITE'=>'ALL',
        'TERRAMITE'=>'PERFORADORAS',
        'TERRAMITE'=>'EXCAVADORAS',
        'TESMEC'=>'ZANJADORAS',
        'TEX-MARC'=>'TRITURADORAS',
        'THOMAS'=>'TRITURADORAS',
        'THOMAS'=>'EXCAVADORAS',
        'THOMAS'=>'MINICARGADORAS',
        'THUNDERBIRD'=>'FELLER BUNCHERS',
        'THUNDERBIRD'=>'JARDINERAS',
        'THUNDERBIRD II'=>'TRITURADORAS',
        'TIGER'=>'EQUIPO FORESTAL',
        'TIGERCAT'=>'FELLER BUNCHERS',
        'TIGERCAT'=>'GRAPPLES',
        'TIGERCAT'=>'LOG LOADERS',
        'TIGERCAT'=>'EQUIPO FORESTAL',
        'TIGERCAT'=>'DESLIZADORAS',
        'TIGERCAT'=>'ZANJADORAS',
        'TIMBCO'=>'ALL',
        'TIMBERJACK'=>'ALL',
        'TIMBERJACK'=>'FELLER BUNCHERS',
        'TIMBERJACK'=>'FORWARDERS',
        'TIMBERJACK'=>'LOG LOADERS',
        'TIMBERJACK'=>'EQUIPO FORESTAL',
        'TIMBERJACK'=>'DESLIZADORAS',
        'TIMBERKING'=>'FELLER BUNCHERS',
        'TIMBERKING'=>'LOG LOADERS',
        'TIMBERKING'=>'EQUIPO FORESTAL',
        'TIMBERLAND'=>'EQUIPO FORESTAL',
        'TIMBERLINE'=>'FELLER BUNCHERS',
        'TIMBERLINE'=>'EQUIPO FORESTAL',
        'TIMBERPRO'=>'EQUIPO FORESTAL',
        'TINK'=>'ZANJADORAS',
        'TOPCON'=>'LASERS',
        'TORO'=>'ALL',
        'TOYOTA'=>'MINICARGADORAS',
        'TRAMAC'=>'ALL',
        'TRAVERSE'=>'MANIPULADOR TELESCÓPICO',
        'TREE FARMER'=>'EQUIPO FORESTAL',
        'TRELAN'=>'CHIP HARVESTERS',
        'TRELAN'=>'ESPAREADORA DE SELLO',
        'TRENCHMASTER'=>'ZANJADORAS',
        'TRENCH-TECH'=>'ZANJADORAS',
        'TRIMBLE'=>'SISTEMAS POSICIÓN GLOBAL',
        'TROJAN'=>'ALL',
        'TUSHOGG'=>'EQUIPO FORESTAL',
        'TUSK'=>'MONTACARGAS',
        'TYMCO'=>'BARREDORAS',
        'U B'=>'MARTILLO HIDRÁULICO',
        'UNIT RIG'=>'TRACTOCAMION',
        'UNIVERSAL'=>'TRITURADORAS',
        'UNIVERSAL'=>'PAVIMENTADORA',
        'UP RIGHT'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'U-SCREEN'=>'TRITURADORAS',
        'USTC'=>'ALL',
        'VALBY'=>'ESPAREADORA DE SELLO',
        'VALLA'=>'GRÚAS TODO TERRENO',
        'VALMET'=>'FELLER BUNCHERS',
        'VALMET'=>'FORWARDERS',
        'VALMET'=>'EQUIPO FORESTAL',
        'VANGUARD'=>'TRACTORES',
        'VERMEER'=>'ALL',
        'VERMEER'=>'ESPAREADORA DE SELLO',
        'VERMEER'=>'COMPACTADORES',
        'VERMEER'=>'CORTADORAS DE CONCRETO',
        'VERMEER'=>'PERFORADORA DIRECCIONAL',
        'VERMEER'=>'EXCAVADORAS',
        'VERMEER'=>'EQUIPO FORESTAL',
        'VERMEER'=>'MINICARGADORAS',
        'VERMEER'=>'CORTADORAS',
        'VERMEER'=>'ZANJADORAS',
        'VERMEER'=>'TUB GRINDERS',
        'VERSALIFT'=>'ALL',
        'VIBROMAX'=>'COMPACTADORES',
        'VINCE HAGAN'=>'ALL',
        'VIPER'=>'TRITURADORAS',
        'VISX'=>'LASERS',
        'VOGELE'=>'PAVIMENTADORA',
        'VOLVO'=>'REPARADORAS',
        'VOLVO'=>'COMPACTADORES',
        'VOLVO'=>'EXCAVADORAS',
        'VOLVO'=>'FELLER BUNCHERS',
        'VOLVO'=>'EQUIPO FORESTAL',
        'VOLVO'=>'MOTONIVELADORAS',
        'VOLVO'=>'TRACTOCAMION',
        'VOLVO'=>'PAVIMENTADORA',
        'VOLVO'=>'TIENDE TUBOS',
        'VOLVO'=>'CARGADORES',
        'VOLVO'=>'MINICARGADORAS',
        'W H O'=>'TUB GRINDERS',
        'WABCO'=>'COMPACTADORES',
        'WABCO'=>'MOTONIVELADORAS',
        'WABCO'=>'TRACTOCAMION',
        'WABCO'=>'RASPADORES',
        'WACKER '=>'ALL',
        'WACKER '=>'COMPACTADORES',
        'WACKER '=>'PLANTAS DE LUZ',
        'WACKER NEUSON'=>'CARGADORES',
        'WACO'=>'MONTACARGAS',
        'WAGNER'=>'COMPACTADORES',
        'WALDON'=>'ALL',
        'WARATAH'=>'DELIMBERS',
        'WARATAH'=>'EQUIPO FORESTAL',
        'WARNER-SWASEY'=>'ALL',
        'WARNER-SWASEY'=>'MONTACARGAS',
        'WARREN CAT'=>'PLANTAS DE LUZ',
        'WAUKESHA'=>'COMPRESORES DE AIRE',
        'WEILER'=>'PAVIMENTADORA',
        'WHITEMAN'=>'ALL',
        'WIGGINS'=>'ALL',
        'WILLMAR'=>'CARGADORES',
        'WILSON'=>'TRANSPORTADORES',
        'WINCO'=>'PLANTAS DE LUZ',
        'WINDHAM'=>'MONTACARGAS',
        'WINPOWER'=>'PLANTAS DE LUZ',
        'WIRTGEN'=>'PAVIMENTADORA',
        'WOLFE'=>'ZANJADORAS',
        'WOODCHUCK'=>'ESPAREADORA DE SELLO',
        'WOODMIZER'=>'EQUIPO FORESTAL',
        'WOODSMAN'=>'ESPAREADORA DE SELLO',
        'WORKFORCE'=>'ELEVADORES TELESCÓPICO, DE PLUMA, DE TIJERA',
        'WORTHINGTON'=>'COMPRESORES DE AIRE',
        'XTREME'=>'MANIPULADOR TELESCÓPICO',
        'YALE'=>'MONTACARGAS',
        'YAMAHA'=>'PLANTAS DE LUZ',
        'YANMAR'=>'TRACTORES',
        'YANMAR'=>'EXCAVADORAS',
        'YANMAR'=>'CARGADORES',
        'YONGMAO'=>'GRÚAS HIDRAÚLICAS',
        'YOUNG'=>'GRAPPLES',
        'YUMBO'=>'EXCAVADORAS',
        'YUTANI'=>'EXCAVADORAS',
        'ZANETIS'=>'ALL',
        'ZETTEL MEYER'=>'CARGADORES',
        'ZIMMERMAN'=>'PAVIMENTADORA');
        
        
        foreach ($data as $marca => $tipo) {
            if($t = TipoProducto::where('nombre', $tipo)->first()){
                $ma = Marca::where('nombre', $tipo)->first();
                if(!$ma){
                    $m = new Marca;
                    $m->tipo_producto_id = $t->id;
                    $m->nombre = $marca;
                    $m->save();
                }
            }else{
        
                $t = new TipoProducto;
                $t->nombre = $tipo;
                $t->linea_negocio_id=1;
                if($t->save()){
                    $m = new Marca;
                    $m->tipo_producto_id = $t->id;
                    $m->nombre = $marca;
                    $m->save();
                }
            }
        
        }
    });
});