defaultLanguage=es
widgetTheme=widget-themes/compact
primaryColor=#009efd
secondaryColor=#808083
labelColor=#ffffff
hideWhenOffline=
autoShowWidget=untilAction
autoShowWidgetAfter=15
contactMail=info@promin.mx
askForMail=true
chatBoxMedia=auto
headerHeight=35
widgetWidth=279
widgetHeight=320
widgetSide=right
widgetOffset=50
mobileBreakpoint=550
maxConnections=5
pollingInterval=5
operatorInitChat=true
onlineTrackInterval=10
messageSound=audio/New Message B.mp3
systemMessageSound=audio/New Message H.mp3
installed=1
sharedFileMaxSize=10
fileSharing=true
gMapsKey=AIzaSyAtw7s9HWES28b3d8Js3Jbd9zy6zsqbG2A
